# Generated by Django 3.1.1 on 2020-10-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201008_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
